remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
title: University of Chicago Data Science Clinic
description: Webpage for the University of Chicago Data Science Clinic
